
backendtest:
  image: amd64/debian:bullseye
  stage: build
  services:
    - name: postgres:13-alpine
    - name: opensearchproject/opensearch:2.0.1
      alias: opensearch
      variables:
        discovery.type: single-node
  tags:
    - docker-build
  variables:
    DEBIAN_FRONTEND: "noninteractive"
    POSTGRES_HOST: postgres
    POSTGRES_DB: idb
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_HOST_AUTH_METHOD: trust
    OS_USER: admin
    OS_PASSWORD: admin
    OS_URI: http://opensearch:9200
  script:
    - apt-get update
    - apt-get install -fuy postgresql-client libfile-slurp-perl libgetopt-long-descriptive-perl libdbi-perl libdbd-pg-perl libjson-perl libmojolicious-perl libmojo-pg-perl libossp-uuid-perl
    - apt-get install -fuy curl
    - ( umask 066 ; echo "postgres:5432:*:$POSTGRES_USER:$POSTGRES_PASSWORD" >~/.pgpass )
    - ( cd backend ; prove -l -v t )
