#!/usr/bin/perl -w

use strict;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use InvDBTest;
use Test::Simple tests => 2;

my $dumprestore="$Bin/../../contrib/dumprestore";
my $simpleone="$Bin/../data/simple1.json";

my $idbt=new InvDBTest();

$idbt->db_clean();
$idbt->db_schema_add("$Bin/../../schema/idb.schema.psql");

my $cmd=sprintf("%s --restore --dbhost postgres --dbname %s --dbuser %s --dbpass %s --file %s",
	$dumprestore,
	$ENV{POSTGRES_DB},
	$ENV{POSTGRES_USER},
	$ENV{POSTGRES_PASSWORD},
	$simpleone);

ok(system($cmd) == 0, "Restore succeeded");
ok($idbt->db_object_by_uuid_exists("b56582e8-a452-4e42-903b-9b5cc2a7267f"), "Object b56582e8-a452-4e42-903b-9b5cc2a7267f exists");

