#!/usr/bin/perl -w

use strict;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use InvDBTest;
use File::Slurp qw/write_file/;
use JSON;

my $dumprestore="$Bin/../../contrib/dumprestore";
my $simpleone="$Bin/../data/simple1.json";

my $idbt=new InvDBTest();

$idbt->db_clean();
$idbt->db_schema_add("$Bin/../../schema/idb.schema.psql");

my $cmd=sprintf("%s --restore --dbhost postgres --dbname %s --dbuser %s --dbpass %s --file %s",
	$dumprestore,
	$ENV{POSTGRES_DB},
	$ENV{POSTGRES_USER},
	$ENV{POSTGRES_PASSWORD},
	$simpleone);

write_file("$Bin/../../backend.conf", 
	sprintf("{ pg => 'postgresql://%s:%s\@postgres/%s', secrets => 'secret' }",
		 $ENV{POSTGRES_USER}, $ENV{POSTGRES_PASSWORD}, $ENV{POSTGRES_DB}));
